apiVersion: apps/v1
kind: Deployment
metadata:
  name: aipub-batch-database
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aipub-batch-database
  template:
    metadata:
      labels:
        app: aipub-batch-database
    spec:
      containers:
        - name: aipub-batch-database
          image: bitnami/postgresql:17.0.0-debian-12-r0
          envFrom:
            - configMapRef:
                name: aipub-batch-database-envs
            - secretRef:
                name: aipub-batch-database-envs
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: aipub-batch-database
              mountPath: /var/lib/postgresql
      volumes:
        - name: aipub-batch-database
          persistentVolumeClaim:
            claimName: aipub-batch-database
---
