apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.pvcSize }}
  storageClassName: {{ .Values.postgresql.storageClassName }}
---
