apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aipub-batch-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.pvcSize }}
  storageClassName: {{ .Values.postgresql.storageClassName | quote }}
---
