apiVersion: v1
kind: Secret
metadata:
  name: aipub-batch-database-envs
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: "{{ .Values.postgresql.password }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: aipub-batch-database-migration-envs
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.postgresql.password }}"
---