apiVersion: v1
kind: Service
metadata:
  name: aipub-batch-database
spec:
  type: ClusterIP
  selector:
    app: aipub-batch-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
