postgresql:
  username: "root"
  password: "Password1@"
  database: "aipub-batch"
  storageClassName: ""
  pvcSize: 2Gi
spring:
  flyway_locations_path: "/etc/database-migration-data/postgresql"
  flyway_locations: "filesystem:/etc/database-migration-data/postgresql"

db_migration:
  image: ten1010-io/aipub-db-migration-tool:1.0.0-SNAPSHOT
  data:
    - V1__Init.sql
